version: "2.0"

services:
  php:
    image: webdevops/php-apache
    volumes:
      - .:/var/www/html:cached
    ports:
       - "80:80"
    links:
      - db:db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gogapi
      MYSQL_PASSWORD: gogpassword
      MYSQL_DATABASE: gogapi